### ISSUE TITLE
Parts of the menu disappear (Wi-Fi, Help and Quit items)

### ISSUE THREAD

**Issue by halo** [halo/LinkLiar#14]
Moved here over from https://github.com/halo/LinkLiar/issues/13#issuecomment-74580303

@GnrGnr wrote:

Installation now works. Yet en1 (WiFi) disappears after authorization of the helper tool from the dropdown. Maybe that's what @kwolk meant/experienced. It doesn't seem to make a difference whether the adapter is active/deativated. Turning wifi on/off also doesn't bring the entry back. En0 works fine though. Like a charm :)

There was some output on the console:

```
16/02/15 22:58:09,467 SecurityAgent[12901]: Failed to initialize IconCache named: com.apple.iconservices with error: Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." (connection to service named com.apple.iconservices) UserInfo=0x7fa869794d50 {NSDebugDescription=connection to service named com.apple.iconservices}
16/02/15 22:58:09,468 SecurityAgent[12901]: Error returned from iconservicesagent: Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." (connection to service named com.apple.iconservices) UserInfo=0x7fa8695127e0 {NSDebugDescription=connection to service named com.apple.iconservices}
16/02/15 22:58:13,934 SecurityAgent[12901]: Error returned from iconservicesagent: Error Domain=NSCocoaErrorDomain Code=4097 "Couldn’t communicate with a helper application." (connection to service named com.apple.iconservices) UserInfo=0x7fa869481840 {NSDebugDescription=connection to service named com.apple.iconservices}
16/02/15 22:58:16,016 Link[12873]: <NSXPCConnection: 0x60000010e8e0> connection to service named com.funkensturm.LinkHelper: Warning: Exception caught during decoding of received reply to message 'getVersionWithReply:', dropping incoming message and calling failure block.

Exception: *** -[NSArray objectsAtIndexes:]: index 2 in index set beyond bounds [0 .. 1]
16/02/15 22:58:17,304 Link[12873]: <NSXPCConnection: 0x60000010e8e0> connection to service named com.funkensturm.LinkHelper: Warning: Exception caught during decoding of received reply to message 'getVersionWithReply:', dropping incoming message and calling failure block.

Exception: *** -[NSArray objectsAtIndexes:]: index 2 in index set beyond bounds [0 .. 1]
16/02/15 22:58:19,558 CoreServicesUIAgent[11649]: unexpected message <OS_xpc_error: <error: 0x7fff7abf9c60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff7abf9f70> { length = 18, contents = "Connection invalid" }
}>
```

Btw: Thanks for the hint to the adequate formatting. I had a quick look yesterday - yet did not identify backticks as the appropriate markdown on first glance.

On another note: Is there any way to shut down LinkLiar except from killing the process/restarting the machine?

*EDIT:* I just realised that there was a "Quit" option before i authorised the helper tool. Yet after its authorisation the quit option is gone; along with en1 and the "help" entry of the pulldown.

**Comment by halo** [comment]
Ok so step by step.


Everything related to `IconCache` is irrelevant I believe. I have those too and not only for LinkLiar but also for other applications.

This one:
```
Exception caught during decoding of received reply to message 'getVersionWithReply:
```

is obviously more serious. Google tells me that we're not alone but unfortunately I cannot reproduce the error which makes it very hard to solve it.

The failing method [is strikingly simple](https://github.com/halo/LinkLiar/blob/master/LinkHelper/Classes/LinkHelper.m#L62-L64) and there should be nothing special there which could cause a bug. However, the

```
index 2 in index set beyond bounds [0 .. 1]
```

gives us a hint. I will make a version of LinkLiar tomorrow which will create a crash report again. With some luck we'll see who it was who called it. I will also try some more google fu.

#### Things you can try meanwhile

* Uninstall the Helpertool as [described in the Readme](https://github.com/halo/LinkLiar#uninstall--upgrading)
* Remove all settings by deleting the setings file with this command (just start the `Terminal` application and paste the command in there: 
```bash
rm ~/Library/Preferences/com.funkensturm.Link.plist
```
* Turn on debugging [as described here](https://github.com/halo/LinkLiar#troubleshooting) and watch the `Console` maybe you see something interesting when you start the application again.
* Think about whether you have anything unusual (external Wi-Fi? unusually old Macbook?)
* In your Network preferences you can create a brand new "Location" at the top. In that new Location you can (almost literally) remove your Wi-Fi interface by selecting it and then pressing the little "-" (minus) button below the list. You can always go back to your default location to get all your network settings back the way they were before the experiment. I'm curious whether it works when you have no Wi-Fi. That might nail down the problem to a smaller scope within the codebase at least.

Thank you for your time.

**Comment by GnrGnr** [comment]
I followed your suggestions step by step but don't see any changes. The console spit out the three already known msg from the security agent and two identical NSXPCConnection errors. The (last) entry from CoreServicesUI did not pop up again this time.

Apart from a second SSD my MacBook doesn't have any weird features or configuration. Yet it's fairly seasoned: A mid 2010 model. As far as i understand bluetooth (LE) changed significantly in later revisions. I wouldn't be surprised if the wifi adapter also has been changed significantly.

When i added a new location, the console showed the following. Unfortunately the wifi (en1) adapter did not reappear.
```
17/02/15 20:11:55,050 Link[14444]: <NSXPCConnection: 0x608000106660> connection to service named com.funkensturm.LinkHelper: Warning: Exception caught during decoding of received reply to message 'getVersionWithReply:', dropping incoming message and calling failure block.

Exception: *** -[NSArray objectsAtIndexes:]: index 2 in index set beyond bounds [0 .. 1]
``` 

I don't know whether this might give you any clue, but the above message also appears, whenever i "open" the helper app. No matter whether i take any action or only scroll over the (in my case remaining) entries for the ethernet (en0) or firewire (fw0) adapter. Even when i simply open and close it again, it shows up. 

Let me know if i can provide you with any further data.

**Comment by kwolk** [comment]
This is what I see:
http://cl.ly/image/3h3U0N0u2t3j

**Comment by GnrGnr** [comment]
That's exactly what i am seeing after authorization of the helper tool. Prior to that, the wifi adapter, "quit" and "help" are on that list as well.

**Comment by halo** [comment]
What on earth is the Firewire adapter doing there? :) I knew [that this](https://github.com/halo/LinkLiar/blob/master/Link/Classes/LinkInterfaces.m#L52-L53) was going to bite me back haha. I assume that is part of the problem. In the new network location, you can add the Wi-Fi again, but could you remove the Firewire?

I will make sure to only include Ethernet and Wi-Fi more reliably than checking for the string `"Wi"` :)

**Comment by GnrGnr** [comment]
Apple introduced Ethernet over Firewire some years ago. I actually used it once (!). Check it out: http://en.wikipedia.org/wiki/IEEE_1394

**Comment by halo** [comment]
Good news! I can reliably reproduce the problem locally. I can confirm that is the issue, a fix is on the way...

**Comment by halo** [comment]
Ok, here's the [new release](https://github.com/halo/LinkLiar/releases/tag/v1.0.3). Thank you for giving it a try :)

**Comment by GnrGnr** [comment]
Moin moin,

LinkLiar works like a charm now. Great work, man!

Nevertheless, two separate thoughts:

When changing the MAC address, the current (wifi) connection becomes unusable. The network adapter probably has to renegotiate its connection once the MAC address changes. If this is the standard procedure, it would be much more convenient to the user if LinkLiar kills the ethernet/wifi connection(s) and re-establishes it once a MAC address change has been initiated by the user. The "suddenly unusable network connection" could become a major headache for people forgetting (or not knowing) that they have to re-establish their network connection. A quick drop and re-connect by LinkLiar could probably avoid this.

Secondly, just a pointer: I just recognised my plugged-in iPhone in the LinkLiar connection list. Because you hid the FireWire adapter, I thought that you might want to hide these very common devices (iPhones, iPads) as well. 
![screen shot 2015-02-22 at 19 03 27](https://cloud.githubusercontent.com/assets/8639993/6319702/c7d71dea-bac6-11e4-8669-5ee4fb18b204.png)

Thanks again for your work. Can't wait to use LinkLiar in real life. Probably at my next "free 30 minute wifi session" at some airport ;)

**Comment by halo** [comment]
Cool! I'm glad it's working. Thank you for your patience with debugging :)

As usual, I extracted your thoughts into new issues :) #15 and #16 and closing this one.
