### ISSUE TITLE
Start LinkLiar on system startup

### ISSUE THREAD

**Issue by aziz** [halo/LinkLiar#17]
I know I can do it myself but it would be nice if application can handle it for me. 
Great app BTW :+1:

**Comment by halo** [comment]
Ah, the way of the Internet, you fix one thing, people want more things ;)

You can thank [this guy](https://github.com/ianyh/IYLoginItem) because he provided dead-simple code for this I just could copy and paste :)

**Comment by aziz** [comment]
Thanks, that was really fast :)

**Comment by aziz** [comment]
BTW, I can't find this option in the menu. maybe we should reopen this issue

**Comment by halo** [comment]
Hm, first open "Help" to make sure you're on version 1.1.1.

Then, **while the menu is open** press the ⌥ key to see the menu item.

**Comment by aziz** [comment]
TNX, didn't know about the option key

**Comment by halo** [comment]
Ok, I'll close it until the next one doesn't find it, then I'll have to rethink my GUI design ;)
