### ISSUE TITLE
Apple TV

### ISSUE THREAD

**Issue by pateboyd** [halo/LinkLiar#18]
I am trying to make my mac address an Apple TV mac to spoof a hotel internet. I cannot apply a manual from the Apple TV.

**Comment by halo** [comment]
Hi. What you will have to do is

1. Find out the MAC address of your Apple TV
2. Turn off your Apple TV
2. Change the MAC address of your laptop to that
3. Register your laptop with the wifi network
4. Turn on your Apple TV

There is no (easy) way to spoof the MAC address of an Apple TV. LinkLiar can only change the address of computers and laptops running Mac OS X.

**Comment by pateboyd** [comment]
That is what I did, but link liar would not accept the MAC address from the appletv. 

Pate Boyd
770-876-7711

**Comment by halo** [comment]
LinkLiar only delegates to the operating system to change the MAC address. If the operating system itself doesn't accept the address, I'm afraid there is not much you can do. If you tell me the MAC address, I can try to assign it to my laptop just so we know whether it's your computer or the address.
