### ISSUE TITLE
Menu Bar icon width

### ISSUE THREAD

**Issue by ajkblue** [halo/LinkLiar#19]
This is quite a nitpicking issue, but I find that on my small MacBook Air screen, all the space I can gain in the menu bar is helpful. I have noticed that the icon width of LinkLiar is a bit wider than other applications in my menu bar, here is is (selected) compared to f.lux: 
![screen shot 2015-10-21 at 4 49 42 pm](https://cloud.githubusercontent.com/assets/9651939/10652578/0effbc2a-7815-11e5-9838-35d7676a50d3.png)
![screen shot 2015-10-21 at 4 50 01 pm](https://cloud.githubusercontent.com/assets/9651939/10652579/0f193e0c-7815-11e5-8e9f-0b5acdb4adde.png)
I know that this is not too big of an issue, but it would be great to shrink the width of the selectable area that LinkLiar uses in the menu bar. The actual icon will still fit perfectly within a smaller size. Looking at LinkLiar's icon compared to the rest of my menu bar apps, the extra space around it becomes more noticeable:
![screen shot 2015-10-21 at 4 51 47 pm](https://cloud.githubusercontent.com/assets/9651939/10652629/66fb847c-7815-11e5-8133-80bb6e06a250.png)

**Comment by halo** [comment]
Wow, nice catch. I always felt something was fishy with the icon, but I could never pinpoint it :) Please give [this prerelease](https://github.com/halo/LinkLiar/releases/tag/1.1.2) a try to see if it works better.

[This guy here](https://github.com/Cocoanetics/AutoIngest/issues/19) had the same problem, luckily he had a solution, too :)

**Comment by ajkblue** [comment]
The icon does fit into that smaller space quite well. I do quite like the new look ;) Everything appears to still work just as expected in this prerelease version.
