### ISSUE TITLE
Request: automatically start on reboot

### ISSUE THREAD

**Issue by jameskhamil** [halo/LinkLiar#28]

**Comment by halo** [comment]
The daemon automatically starts on boot if you check "Run in background" in the settings. But I assume that you mean the menu bar icon?

I had that implemented earlier, but Apple changed things in Sierra so I decided to wait until the documentation was updated on which way was the preferred way to implement this.

I also want this feature myself, I'll look into whether things have improved now.

**Comment by halo** [comment]
Hi! Would you mind giving it a try?

https://github.com/halo/LinkLiar/releases/tag/2.1.1

**Comment by jameskhamil** [comment]
Will check this out, thanks for this and all the replies!
