### ISSUE TITLE
How to confirm its working?

### ISSUE THREAD

**Issue by enigmavision** [halo/LinkLiar#32]
I used macchanger to see if the mac address in linkliar would match to see if it is really working, how can we confirm its actually working? ie. what command can we enter to see the mac address matches what it says in linkliar?

Thanks

**Comment by halo** [comment]
Hi!

Internally, LinkLiar [performs this command](https://github.com/halo/LinkLiar/blob/8f4811a4cdd694942c27e33baff5859e388d8361/LinkTools/Ifconfig.swift#L55) to determine the MAC address of an interface:

```bash
 ifconfig en0
```

Every time you open the LinkLiar menu, this command is executed. So you can be sure that whatever you see in LinkLiar is accurate. See also [this issue](https://github.com/halo/LinkLiar/issues/29).

However, to go really sure, there is only one way to find out which MAC address is actually being used: you would need to inspect your network traffic using a tool such as [Wireshark](https://www.wireshark.org/).
