### ISSUE TITLE
No longer works with the 2018 MBPs

### ISSUE THREAD

**Issue by mighty124** [halo/LinkLiar#33]
Has anyone ever managed to find a way to spoof MAC addresses on macos for 2018 MBPs? Since it looks like even the manual sudo ifconfig en0 ether xx:xx:xx:xx:xx:xx no longer changes anything...
 
Thanks for the help!

**Comment by halo** [comment]
Hi thanks for your report!

I only have a MBP 2017 so unfortunately I cannot verify that.

But reports are rolling in [over at WifiSpoof](
https://sweetpproductions.com/support/showthread.php?tid=625) that it stopped working on brand new MacBooks. It's a commercial product so they'll try hard to find out what's going on.

You could try the free trial version of wifispoof.com to confirm that it's not working on your MacBook. It would be rather radical if Apple stopped this functionality just like that. 🤔

(Also, please try a few different MAC addresses, also with known Apple vendor prefixes. Because I know that a whole range of addresses won't be accepted whatever you do. But you probably already tried.)

**Comment by halo** [comment]
More [reports](
https://github.com/feross/SpoofMAC/issues/87), doesn't look good.

**Comment by hktalent** [comment]
me too

**Comment by hktalent** [comment]
not work
```
echo $rtpswd | sudo -S ifconfig en0 ether f0:18:98:bb:aa:22
```

**Comment by madhavajay** [comment]
Seems to be working for these guys?
https://twitter.com/SweetP_Pro/status/1065139270309085184

**Comment by madhavajay** [comment]
Ahh yes of course, sorry, I confounded Mojave with MBP 2018. Thats a pity, I just got my MBP 2018 and was pretty disappointed to find LinkLiar doesnt work. :(

I guess this would still work with a third party WiFi Dongle though right?

**Comment by halo** [comment]
> I just got my MBP 2018 and was pretty disappointed to find LinkLiar doesnt work. :(

I'm sorry to hear that. Given that Apple cares a lot for iPhone MAC addresses to be random, I can only hope that this was a mistake on their side. But then again I understand they might want to be the good guys for airport internet providers.

I was afraid this were be a pure hardware limitation, until there was [one guy](https://github.com/feross/SpoofMAC/issues/87#issuecomment-430923760) who said it worked with *factory-shipped* High Sierra, but others said it didn't. So we simply don't know.

It would be great if [you could](https://github.com/feross/SpoofMAC/issues/87#issuecomment-430688350) boot your MacBook with another operating system, say, Ubuntu directly from a USB stick and try to change your MAC. If it works, we'd immediately know this is a software blockage, not a hardware issue.

> I guess this would still work with a third party WiFi Dongle though right?

Yes, that's what I've read. But just as with everything, some dongles work, some don't. That's up to the dongle vendor, I suppose. I have more luck with USB-A Ethernet dongles than USB-C on a 2017 MBP.

**Comment by madhavajay** [comment]
I can try, although I heard disabling safe boot is required?

**Comment by halo** [comment]
Hm, not according to [this guide](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos). But I haven't tried.

Maybe you meant when installing Ubuntu on the local disk instead of running it directly from the USB stick?

**Comment by Suleman-Elahi** [comment]
I read on reddit that in MAC High Sierra change MAC address by ensuring the first three octets of the address stay the same as the hardware address.

XX:XX:XX:YY:YY:YY

Leave XX’s the same as hardware address, change YY’s.

**Comment by halo** [comment]
As far as I can tell, this works again as of macOS Catalina, regardless of the MacBook production year. I tested it myself on a 2019 MacBook Pro and [similar reports have been coming in](https://github.com/feross/SpoofMAC/issues/87#issuecomment-539864016).

Closing this for now, thank you for reporting this issue.
