### ISSUE TITLE
Spoof as early as possible during boot (when deamon starts up)

### ISSUE THREAD

**Issue by JamieJ1** [halo/LinkLiar#34]
Does this app start spoofing my MAC address as soon as I restart my laptop? Or do I have to start the app first? (sorry didnt know where else to post questions)

**Comment by halo** [comment]
Hi! This is the right place to ask the question :)

Have a look on [this page](https://halo.github.io/LinkLiar/settings.html). If you turn on the "Run in Background" option, a daemon with root privileges will be activated. 

That daemon is designed to spoof your MAC address (according to your desired configuration)

* when your network [conditions change](https://github.com/halo/LinkLiar/blob/ed66bb0c5e691c04d374d6cd1c6aa4567e121ee8/linkdaemon/Classes/LinkDaemon.swift#L58-L61)
* when your computer goes to [sleep or powers off](https://github.com/halo/LinkLiar/blob/ed66bb0c5e691c04d374d6cd1c6aa4567e121ee8/linkdaemon/Classes/LinkDaemon.swift#L63-L71)
* when the json config [file changed](https://github.com/halo/LinkLiar/blob/ed66bb0c5e691c04d374d6cd1c6aa4567e121ee8/linkdaemon/Classes/LinkDaemon.swift#L53-L56)
* every [10 minutes](https://github.com/halo/LinkLiar/blob/master/LinkTools/IntervalTimer.swift#L21) (just in case)

Now, "network conditions changed", happens roughly when you come to your login screen after boot, so to answer your question, yes, it spoofs on boot.

But there is a slight chance that your real MAC address will be exposed for a second or so, before the spoofing takes effect. Just like plugging in a wifi-dongle will expose its MAC address for a short time.

However, after booting, your MAC address should **remain** spoofed at all times, given that the daemon is alive.

(To go sure, I should let the daemon **always** run once whenever it is activated, i.e. as early as possible on boot. I'll keep this issue open until that is solved. Just as a fallback security I guess. Can't hurt.)

**Comment by AnonymousAnonymousAnonymous** [comment]
Thank you very much for your work and maintenance on this app. I have it on my top 3 must-have Mac apps ever, since I left Windoze many moons ago.

**Comment by halo** [comment]
I checked the code and [it already does what we want](https://github.com/halo/LinkLiar/blob/master/LinkTools/NetworkObserver.swift#L38-L40). So I'm closing this issue.

By the way, there is a pre-release that you might want to try out:
https://github.com/halo/LinkLiar/releases/tag/3.0.0

Thank you for your patience.
