### ISSUE TITLE
wrong mac displayed in menu bar

### ISSUE THREAD

**Issue by cyb3rw0lf** [halo/LinkLiar#57]
As shown in the picture, when using `Random` or `Define manually` methods linkliar is displaying a different mac address (not sure where it come from).
If using the `Keep Original` method then it display the correct one

<img width="565" alt="linkliar wrong mac" src="https://user-images.githubusercontent.com/25265715/198572120-c0dd7354-ef3c-4ccf-b05e-5e23d2768af3.png">

**Comment by cyb3rw0lf** [comment]
Linkliar version: 3.2.0
macOS version: 13.0
Apple M1

**Comment by halo** [comment]
Hi! I don't seem to be able to reproduce this issue locally. In fact, LinkLiar runs `ifconfig` [under the hood](https://github.com/halo/LinkLiar/blob/6937c8beb3850a34d31821143017467cfe70f606/LinkTools/Ifconfig.swift#L53-L60) to determine the currently used MAC address.

Two thoughts:

1. Do you see anything out-of-the-ordinary in the logs? You can print the logs to STDOUT simply by running `/Applications/LinkLiar.app/Contents/Resources/logs` 

2. Do you have "anonymize logs" turned on, by any chance? That would explain the problem, I think.

<img width="375" alt="Screenshot 2023-04-19 at 06 48 05" src="https://user-images.githubusercontent.com/11441/232969521-0460f1ee-1581-4893-a614-4a385587d61a.png">

**Comment by halo** [comment]
I'm planning on releasing a new LinkLiar version for macOS Sonoma in the coming weeks.

I'll close this issue for now. If something new should surface, please feel free to open it again. Thank you!
