### ISSUE TITLE
It's still in Background apps list

### ISSUE THREAD

**Issue by yelloduxx** [halo/LinkLiar#65]
I have uninstalled the app (the 4th version delta), but it's still in background running apps list. How can I remove it?
MBA 15 M3 Sonoma 14.5

![CleanShot 2024-06-10 at 22 17 41](https://github.com/halo/LinkLiar/assets/104713086/af568276-0b11-448b-a7df-d97ccdb5bea6)

**Comment by halo** [comment]
Hi! Thank you for asking.

If you delete `LinkLiar.app` and restart your computer, there should be no reference to it any longer.

If that does not work, you could try to remove it with this button in the LinkLiar settings:

<img width="638" alt="Screenshot 2024-06-11 at 10 44 57" src="https://github.com/halo/LinkLiar/assets/11441/a1252756-30b6-4264-8785-d2143daa5b6d">

Let me know how it goes.

**Comment by yelloduxx** [comment]
Hi, Halo! 

Nope, it didn't work. I tried to uninstall it with mac options (to remove linkliar from apps to the bin) and rebbot, it didn't work. Then I installed it again, unregistered the daemon, deleted it via special app cleaner and rebooted, but it didn't work too. But then I installed CleanMyMac X and it said that some app was uninstalled incorrectly. I clicked on "remove" and it remove it completely, and it solved the issue.

**Comment by halo** [comment]
Interesting. One thing I noticed: I'm confident, that the latest version (4.0.0) should have an icon here:

<img width="464" alt="Screenshot 2024-06-11 at 18 45 17" src="https://github.com/halo/LinkLiar/assets/11441/947a9f54-7112-4cdc-9a2e-018ad92b8d57">

But you didn't have an icon in your screenshot. 

Did you have a previous version of LinkLiar installed before? Because earlier versions are a little harder to uninstall.

**Comment by yelloduxx** [comment]
> the latest version (4.0.0) should have an icon here

It had the icon before removing. After uninstalling it had no icon, but still it was in background running apps list

**Comment by halo** [comment]
I could not find anything that would allow me to remove the item from the list programmatically. I'm [using](https://github.com/halo/LinkLiar/blob/a9965e841a1eae877b780367878749289e826e8c/LinkLiar/Classes/Controller.swift#L45) the function [unregister](https://developer.apple.com/documentation/servicemanagement/smappservice/unregister()) to undo background service. It does unregister the daemon but that apparently doesn't remove anything from the list (think of the list like a list of things you might wish to authorize again in the future).

There is a command `sfltool resetbtm` that you can run in Terminal to clear the cache of that list. It completely removes all items and repopulates them "without ghosts" after a reboot.

<img width="495" alt="Screenshot 2024-08-13 at 14 20 48" src="https://github.com/user-attachments/assets/73cbd012-5d80-47ec-b00d-dce9e21b2f37">

I suspect that CleanMyMac X does something similar to clearing the list cache, but I haven't been able to figure out what exactly.

Previous research:
* https://developer.apple.com/forums/thread/713830?answerId=728707022#728707022
* https://superuser.com/a/1769196
* https://support.apple.com/guide/deployment/manage-login-items-background-tasks-mac-depdca572563/web

You are completely right to report this issue, but until there is an official way by Apple to solve this problem, I'd like to close it. I will add instructions to the uninstall section though, to alleviate the confusion.
