### ISSUE TITLE
4.0.0 Sonoma Experimental Beta - The changed mac address is not updated in the UI after sleep and relogin

### ISSUE THREAD

**Issue by ghost** [halo/LinkLiar#66]
mac address changes correctly after sleep and relogin, but it is not updated in the UI. 
mac address change is only reflected in the UI when the app is closed and restarted.

**Comment by halo** [comment]
Hi 👋🏻  and thank you for your report.

- Does the GUI update when you change your network settings? Such as unplugging a network cable or changing your IP address?
- Does this always happen or only sometimes?
- Does the problem go away after 11 minutes? If I remember correctly, there is a periodic refresh after 10 minutes, in case the change was not detected.

Is there a reason why you use `3.0.3` or could you try out the new beta version at https://github.com/halo/LinkLiar/releases ?

The old version is hard to maintain. I don't think I'll have time to fix that (I hardly find the time to polish the beta).
