### ISSUE TITLE
Hardware/Original MAC

### ISSUE THREAD

**Issue by 360fun** [halo/LinkLiar#9]
Hi, is it possible to add a "revert to original" feature? or just show the original MAC?

Like in "ChangeMAC 1.6", another similar utility, you can see the HW MAC and the fake MAC, then revert:
![s](https://f.cloud.github.com/assets/844090/1093907/60a92b0a-16b6-11e3-8d11-f888295d98a1.png)

Would make this utility perfect, THANKS! =)

**Comment by halo** [comment]
I found a way to do this. Looking forward to implementing this soon.

**Comment by halo** [comment]
Would you mind giving the latest release a try?

**Comment by halo** [comment]
I'll close this because I think it's solved

**Comment by 360fun** [comment]
Yeah, thanks! :D
